---
label: Product
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- type: text
  name: priceBefore
  label: priceBefore
- type: text
  name: shortDescription
  label: shortDescription
- type: number
  name: productID
  label: productID
- type: text
  name: type
  label: type
  hidden: true
  default: products
- type: text
  name: optionLable
  label: optionLable
- type: list
  name: options
  label: options
- type: field_group_list
  name: images
  label: images
  fields:
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
pages:
- content/products/handbag-and-purse.md
