---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
  config:
    required: false
    min: 
- type: datetime
  name: date
  label: date
  hidden: false
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
  config:
    required: true
    min: 1
- type: text
  name: priceBefore
  label: priceBefore
- type: text
  name: shortDescription
  label: shortDescription
- name: productid
  type: number
  label: productID
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- type: text
  name: type
  label: type
  default: products
  hidden: true
- type: field_group_list
  name: images
  label: images
  fields:
  - type: file
    name: image
    label: image
pages:
- content/products/test-1.md
- content/products/test.md
